version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: blog-db
    restart: always
    environment:
      POSTGRES_DB: blogdb
      POSTGRES_USER: maynaou
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh  # Ajouter le script d'initialisation


  backend:
    build: .
    container_name: blog-backend
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/blogdb
      SPRING_DATASOURCE_USERNAME: maynaou
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
    ports:
      - "8080:8080"

volumes:
  pgdata:
